version: '3.4'
services:
  postgresql:
    image: postgres:11
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - './db:/docker-entrypoint-initdb.d'
