version: '3.7'
services:
  postgresql:
    image: postgres:11
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      # copy the sql script to fill tables
    #      - ./sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    restart: always
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=mysecretpassword
#      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
